##/vis/open OGLIX
#/vis/open VRML2FILE
##/vis/open DAWNFILE
#
## Z-X view
#/vis/viewer/set/upVector 1 0 0
#/vis/viewer/set/viewpointThetaPhi 90. 90.
#
## X-Y view
##/vis/viewer/set/viewpointThetaPhi 0. 90.

/samurai/geometry/Dipole/Angle 30 deg
/samurai/geometry/Dipole/FieldFile /home/kondo/exp/samurai/field_map/120405-bn_stage-d-540,0A-3,0T-map.bin
/samurai/geometry/Dipole/FieldFactor 1.0

/samurai/geometry/NEBULA/ParameterFileName geometry/NEBULA_samurai21_1.csv
/samurai/geometry/NEBULA/DetectorParameterFileName geometry/NEBULA_Detectors_samurai21_1.csv

/samurai/geometry/NeuLAND/ParameterFileName geometry/NeuLAND_samurai21_1.csv
/samurai/geometry/NeuLAND/DetectorParameterFileName geometry/NeuLAND_Detectors_samurai21_1.csv

/samurai/geometry/Target/Position 0 0 -4500 mm
# Dayone target position
#/samurai/geometry/Target/Position 0 0 -3867.28 mm

/samurai/geometry/FillAir false

# must be called after definition of detector positions
/samurai/geometry/Update

#/vis/drawVolume
#/vis/scene/endOfEventAction accumulate
#/vis/scene/add/trajectories smooth
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1

/action/file/RunName nebula_neuland_1_28o_psdecay_
/action/file/SaveDirectory root/examples/
/action/file/OverWrite y

/action/data/NEBULA/StoreSteps false
/action/data/NeuLAND/StoreSteps false
#
#/action/gun/SkipNeutron true

/action/gun/Type Tree 
/action/gun/tree/InputFileName root/examples/inputtree_28o_example.root
/action/gun/tree/TreeName tree_input

#should be tested
#/process/had/cascade/crossSectionScale 0.1

#/run/setCut 1 cm
#/run/setCutForAGivenParticle e- 1 cm
#/run/setCutForAGivenParticle proton 1 cm

/action/gun/tree/beamOn 0
