##/vis/open OGLIX
#/vis/open VRML2FILE
##/vis/open DAWNFILE
#
## Z-X view
#/vis/viewer/set/upVector 1 0 0
#/vis/viewer/set/viewpointThetaPhi 90. 90.
#
## X-Y view
##/vis/viewer/set/viewpointThetaPhi 0. 90.

/samurai/geometry/Dipole/Angle 30 deg
/samurai/geometry/Dipole/FieldFile /home/kondo/exp/samurai/field_map/120405-bn_stage-d-540,0A-3,0T-map.bin
/samurai/geometry/Dipole/FieldFactor 1.0

/samurai/geometry/NEBULA/ParameterFileName geometry/NEBULA_samurai21_1.csv
/samurai/geometry/NEBULA/DetectorParameterFileName geometry/NEBULA_Detectors_samurai21_1.csv

/samurai/geometry/NeuLAND/ParameterFileName geometry/NeuLAND_samurai21_1.csv
/samurai/geometry/NeuLAND/DetectorParameterFileName geometry/NeuLAND_Detectors_samurai21_1.csv

/samurai/geometry/Target/Position 0 0 -4500 mm

# must be called after definition of detector positions
/samurai/geometry/Update

#/vis/drawVolume
#/vis/scene/endOfEventAction accumulate
#/vis/scene/add/trajectories smooth
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1

/action/data/NEBULA/StoreSteps false
/action/data/NeuLAND/StoreSteps false

/action/file/RunName nebula_neuland_1_1n_
/action/file/SaveDirectory root/examples/
/action/file/OverWrite y

/action/gun/Type Tree 
/action/gun/tree/InputFileName root/examples/inputtree_1n_example.root
/action/gun/tree/TreeName tree_input
/action/gun/Z 0
/action/gun/A 1
/action/gun/SetBeamParticle
/action/gun/Energy 200 MeV

/action/gun/tree/beamOn 0
