#/vis/open OGLIX
#/vis/open VRML2FILE
#/vis/open DAWNFILE

# Z-X view
/vis/viewer/set/upVector 1 0 0
/vis/viewer/set/viewpointThetaPhi 90. 90.

# X-Y view
#/vis/viewer/set/viewpointThetaPhi 0. 90.

#zoom
/vis/viewer/zoom 3

/samurai/geometry/Dipole/Angle 30 deg
#/samurai/geometry/Dipole/Angle -30 deg
#
/samurai/geometry/Dipole/FieldFile /home/kondo/exp/samurai21/geant4/smsimulator3.6/work/sim_samurai21/field_map/141114-2,9T-3000.bin
/samurai/geometry/Dipole/FieldFactor 1.0

/samurai/geometry/NEBULA/ParameterFileName geometry/NEBULA_samurai21_1.csv
/samurai/geometry/NEBULA/DetectorParameterFileName geometry/NEBULA_Detectors_samurai21_1.csv

/samurai/geometry/NeuLAND/ParameterFileName geometry/NeuLAND_samurai21_1.csv
/samurai/geometry/NeuLAND/DetectorParameterFileName geometry/NeuLAND_Detectors_samurai21_1.csv

/samurai/geometry/Target/Position 0 0 -4367 mm
/samurai/geometry/FDC2/Position 496.715 0 4128.48 mm
/samurai/geometry/HODF24/Position 496.715 0 4866.48 mm

# must be called after definition of detector positions
/samurai/geometry/Update

/action/file/RunName run0466_
/action/file/SaveDirectory root/brho_func/
/action/file/OverWrite y

/vis/drawVolume

/vis/scene/endOfEventAction accumulate
/vis/scene/add/trajectories smooth
/vis/scene/add/axes 0 0 0 5000 mm
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1


/action/file/OverWrite y

#/tracking/verbose 1

/action/gun/Type Tree
/action/gun/tree/InputFileName root/brho_func/input_run0466.root
/action/gun/tree/TreeName tree_input
/action/gun/tree/beamOn 0
