/samurai/geometry/Dipole/Angle 30 deg

#/samurai/geometry/Dipole/FieldFile ../field_map/2,6750T445,93A.table
/samurai/geometry/Dipole/FieldFile ../field_map/2,6750T445,93A.bin
/samurai/geometry/Dipole/FieldFactor 1.0

/dali/ParameterFileName         geometry/DALI_tm1510.csv
/dali/DetectorParameterFileName geometry/DALI_Detectors_tm1510.csv
/dali/ResolutionFileName        geometry/DALI_Resolution_s021.csv

/samurai/geometry/NEBULA/ParameterFileName         geometry/NEBULA_samurai21.csv
/samurai/geometry/NEBULA/DetectorParameterFileName geometry/NEBULA_Detectors_samurai21.csv

/samurai/geometry/NeuLAND/ParameterFileName         geometry/NeuLAND_samurai21.csv
/samurai/geometry/NeuLAND/DetectorParameterFileName geometry/NeuLAND_Detectors_samurai21.csv

/samurai/geometry/Target/Position 0.0  0 -4139    mm
/samurai/geometry/FDC2/Position  -3.19 0  4126.92 mm
/samurai/geometry/ICF/Position    0.0  0  5106.92 mm
/samurai/geometry/HODS/Position  -3.55 0  5791.92 mm

# must be called after definition of detector positions
/samurai/geometry/Update

#######################################
### Visualization
#######################################
#/vis/open OGLIX
/vis/open VRML2FILE
#/vis/open DAWNFILE

/vis/viewer/set/upVector 1 0 0

# Z-X view
/vis/viewer/set/viewpointThetaPhi 90. 90.
# X-Y view
#/vis/viewer/set/viewpointThetaPhi 0. 90.

#zoom
/vis/viewer/zoom 1.8
#/vis/viewer/zoom 7.0

/vis/drawVolume

/vis/scene/endOfEventAction accumulate
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
#######################################
#######################################

/action/file/OverWrite y
/action/file/RunName example_pencil
/action/file/SaveDirectory root/examples/

/action/gun/Type Pencil
/action/gun/Z 0
/action/gun/A 1
/action/gun/SetBeamParticle
/action/gun/Energy 200 MeV

/run/beamOn 1

