/control/suppressAbortion 1

/samurai/geometry/Dipole/Angle 30 deg

#/samurai/geometry/Dipole/FieldFile ../field_map/2,6750T445,93A.table
#/samurai/geometry/Dipole/FieldFile ../field_map/2,6750T445,93A.bin
#/samurai/geometry/Dipole/FieldFile ../field_map/2,5750T417.78A.table
#/samurai/geometry/Dipole/FieldFile ../field_map/2,5750T417.78A.bin
#/samurai/geometry/Dipole/FieldFile ../field_map/2,4750T390.83A.table
/samurai/geometry/Dipole/FieldFile ../field_map/2,4750T390.83A.bin

/samurai/geometry/Dipole/FieldFactor 1.0

/dali/ParameterFileName         geometry/DALI_tm1510.csv
/dali/DetectorParameterFileName geometry/DALI_Detectors_tm1510.csv
/dali/ResolutionFileName        geometry/DALI_Resolution_samurai21.csv

/samurai/geometry/NEBULA/ParameterFileName         geometry/NEBULA_samurai21.csv
/samurai/geometry/NEBULA/DetectorParameterFileName geometry/NEBULA_Detectors_samurai21.csv

/samurai/geometry/NeuLAND/ParameterFileName         geometry/NeuLAND_samurai21.csv
/samurai/geometry/NeuLAND/DetectorParameterFileName geometry/NeuLAND_Detectors_samurai21.csv

/samurai/geometry/Target/Position 0.0  0 -4139    mm
/samurai/geometry/FDC2/Position  -3.19 0  4126.92 mm
/samurai/geometry/ICF/Position    0.0  0  5106.92 mm
/samurai/geometry/HODS/Position  -3.55 0  5791.92 mm

# must be called after definition of detector positions
/samurai/geometry/Update

#######################################
### Visualization
#######################################
##/vis/open OGLIX
#/vis/open VRML2FILE
##/vis/open DAWNFILE
#
#/vis/viewer/set/upVector 1 0 0
#
## Z-X view
#/vis/viewer/set/viewpointThetaPhi 90. 90.
## X-Y view
##/vis/viewer/set/viewpointThetaPhi 0. 90.
#
##zoom
#/vis/viewer/zoom 1.8
##/vis/viewer/zoom 7.0
#
#/vis/drawVolume
#
#/vis/scene/endOfEventAction accumulate
#/vis/scene/add/trajectories smooth
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
#########################################
#########################################

/action/file/OverWrite y
/action/file/RunName example_fng
/action/file/SaveDirectory root/examples/

/action/gun/Type Tree
/action/gun/tree/InputFileName root/examples/inputtree_fng.root
/action/gun/tree/TreeName tree_input

# generate 1000 events
/action/gun/tree/beamOn 1000

# generate NumOfEvents = tree->GetEntries()
#/action/gun/tree/beamOn 0


