# =========================================================================
# =========================================================================
#
# Geometry for the SAMURAI Dayone experiment
#
#-----------------------------------
# field map file
/samurai/geometry/Dipole/FieldFile ../field_map/141114-3,0T-3000.table
/samurai/geometry/Dipole/Angle 30 deg
/samurai/geometry/Dipole/FieldFactor 1.0

#-----------------------------------
# FDC2 position
# Z should be distance from MAGcenter to FDC2 Z=0 plane
/samurai/geometry/FDC2/Position 719.36 0 4126.915 mm

#-----------------------------------
# HODF position
# Z should be distance from MAGcenter to HOD plane
# Z is Minakata value - 51mm

# D ("701mm") setting for 22C,19B in LogBook definition
/samurai/geometry/HOD/Position 986.515 0 5116.35 mm

#-----------------------------------
# NEBULA
/samurai/geometry/NEBULA/ParameterFileName geometry/NEBULA_Dayone.csv
/samurai/geometry/NEBULA/DetectorParameterFileName geometry/NEBULA_Detectors_Dayone.csv
#

#-----------------------------------
# UPDATE (should be called after changing geometry)
/samurai/geometry/Update
