/control/suppressAbortion 1

/samurai/geometry/Dipole/Angle 30 deg

/samurai/geometry/Dipole/FieldFile /home/kondo/exp/samurai21/geant4/smsimulator/smsimulator/work/sim_samurai21/field_map/141114-2,9T-3000.bin
/samurai/geometry/Dipole/FieldFactor 1.0

/samurai/geometry/NEBULA/ParameterFileName geometry/NEBULA_samurai21.csv
/samurai/geometry/NEBULA/DetectorParameterFileName geometry/NEBULA_Detectors_samurai21.csv

/samurai/geometry/NeuLAND/ParameterFileName geometry/NeuLAND_samurai21.csv
/samurai/geometry/NeuLAND/DetectorParameterFileName geometry/NeuLAND_Detectors_samurai21.csv

# upstream of MINOS
/samurai/geometry/Target/Position 0 0 -4367 mm
/samurai/geometry/FDC2/Position 496.715 0 4128.48 mm
/samurai/geometry/HODF24/Position 496.715 0 4866.48 mm

# must be called after definition of detector positions
/samurai/geometry/Update

/action/file/OverWrite y
/action/file/RunName 29ne_lh2_27f_
/action/file/SaveDirectory root/1n/

/action/gun/Type Tree
/action/gun/tree/InputFileName /home/kondo/exp/samurai21/anaroot/macros/Ana1n/generated_29ne_lh2_27f.root
/action/gun/tree/TreeName tree_input

# do not store the geant4 step information
/action/data/NEBULA/StoreSteps false
/action/data/NeuLAND/StoreSteps false

# do not include resolution
#/action/data/NEBULA/Resolution false
#/action/data/NeuLAND/Resolution false

# generate 1000 events
#/action/gun/tree/beamOn 1000

# generate NumOfEvents = tree->GetEntries()
/action/gun/tree/beamOn 0


